import LocationPageTemplate from '../../../components/feature/LocationPageTemplate';

export default function LocationPage() {

  return (
    <LocationPageTemplate
      metaTitle="Garden City, NY Garage Door Repair & Custom Installation | Smart Garage Doors"
      metaDescription="Premium garage door service in Garden City, NY. Carriage-house & custom doors, quiet belt-drive smart openers, same-day repair. Licensed & insured. (914) 557-6816."
      keywords="Garden City garage door repair, garage door installation Garden City NY, carriage house garage doors Garden City, garage door spring replacement Garden City, quiet garage door opener Nassau"
      slug="/garden-city-ny/"
      cityName="Garden City"
      stateCode="NY"
      stateName="New York"
      geo={{ latitude: '40.7268', longitude: '-73.6343' }}
      heroImage="https://imagedelivery.net/qHBP5gILWOpC78ZgZPcRpg/251bb224-5425-49d4-7ab9-6fceaf7a3b00/hero"
      neighborhoods={[{"name":"Estates Section","description":"Garden City's grandest streets, lined with stately colonials and Tudors on deep lots. We install carriage-house and custom wood-look doors designed to match the home's original architecture, with hardware and window inserts chosen to suit."},{"name":"Central Section","description":"Classic center-hall colonials near the village core. Popular projects here include premium insulated steel doors with raised panels and quiet LiftMaster belt-drive openers for garages close to living space."},{"name":"Mott Section","description":"A historic neighborhood of handsome Victorians and colonials north of the LIRR. We help homeowners choose period-appropriate carriage-style designs and decorative hardware that respect the streetscape."},{"name":"Eastern Section","description":"Established blocks of Tudors and brick colonials with attached and detached garages. We handle spring and cable replacement, track repair, and full door upgrades with clean, careful installation."},{"name":"Western Section","description":"Tree-lined streets of traditional homes near Garden City's golf and club grounds. Insulated doors with architectural detailing are a frequent recommendation, paired with WiFi smart openers."},{"name":"Stewart Manor border","description":"We serve homes along the Stewart Manor and Franklin Square border with the same premium parts, upfront pricing, and warranty-backed workmanship as the rest of Garden City."}]}
      reviews={[]}
      faqs={[{"question":"What does a new garage door installation cost in Garden City?","answer":"New installation starts from $800 for standard doors; premium insulated, carriage-style, and custom wood doors run higher. You get a detailed, itemized quote before any work begins — no surprises."},{"question":"Is it better to repair or replace my Garden City garage door?","answer":"If the door itself is in good shape, repairs are usually the smart choice: most repairs run $150–$300, spring replacement $175–$350, and opener repair $150–$350. If panels are damaged, the door is uninsulated, or it no longer suits the home, we'll walk you through replacement options honestly — we never push a new door when a repair will do."},{"question":"Can you install a quiet garage door opener with smartphone control?","answer":"Yes. We install LiftMaster belt-drive openers — dramatically quieter than older chain drives, which matters in Garden City homes with bedrooms or living space over the garage. Every install includes full WiFi and myQ app setup so you can control and monitor the door from anywhere."},{"question":"How fast can you get to Garden City?","answer":"Our Nassau County team covers Garden City and the surrounding communities every week. We give you an honest ETA when you call, and same-day appointments are often available."},{"question":"Can you match a new garage door to my colonial or Tudor home?","answer":"That's our specialty in Garden City. From the Estates Section to the Mott Section, we help you select carriage-house designs, panel profiles, window grilles, and finishes from Clopay, Wayne Dalton, and Amarr that complement the home's architecture and the neighborhood's character."},{"question":"Do you handle Garden City's design and permit considerations?","answer":"Garden City takes its streetscapes seriously, and exterior changes on some blocks warrant a careful, architecturally appropriate choice. We guide you toward styles consistent with the village's traditional character and provide the product specs and documentation you may need for village or association approval."}]}

    />
  );
}
