import LocationPageTemplate from '../../../components/feature/LocationPageTemplate';

export default function LocationPage() {

  return (
    <LocationPageTemplate
      metaTitle="Rockville Centre, NY Garage Door Repair & Carriage Door Installation | Smart Garage Doors"
      metaDescription="Garage door repair & premium installation in Rockville Centre, NY. Carriage-style doors for village colonials, quiet belt-drive openers, upfront pricing. (914) 557-6816."
      keywords="Rockville Centre garage door repair, garage door installation Rockville Centre NY, carriage house garage doors Rockville Centre, quiet garage door opener Nassau County, garage door replacement RVC"
      slug="/rockville-centre-ny/"
      cityName="Rockville Centre"
      stateCode="NY"
      stateName="New York"
      geo={{ latitude: '40.6584', longitude: '-73.6412' }}
      heroImage="https://imagedelivery.net/qHBP5gILWOpC78ZgZPcRpg/251bb224-5425-49d4-7ab9-6fceaf7a3b00/hero"
      neighborhoods={[{"name":"Canterbury area","description":"Gracious brick and stucco colonials on some of the village's most admired blocks. Carriage-house doors with divided-light windows and decorative hardware match the neighborhood's classic architecture beautifully."},{"name":"Old Canterbury","description":"The historic heart of Canterbury with Tudor and colonial revival homes from the 1920s. Period-appropriate carriage-style doors in insulated steel deliver the original look with modern performance and warranty-backed installation."},{"name":"Hempstead Ave corridor","description":"A busy mix of single-family homes and multi-family buildings along Hempstead Avenue. We service residential doors, shared building garages, and gates with the same upfront pricing."},{"name":"Lakeview border","description":"Comfortable colonials and capes along the village's northern edge. Spring replacement, opener upgrades, and insulated door installs are our most common calls in these blocks."},{"name":"South Side","description":"Family colonials and splits south of Sunrise Highway, most with attached garages. Quiet LiftMaster belt-drive openers and insulated doors keep noise out of the living space above and beside the garage."},{"name":"LIRR village core","description":"Homes within walking distance of the Rockville Centre station, where curb appeal carries real value. A premium carriage-style or raised-panel door is one of the most visible upgrades these classic South Shore houses can get."}]}
      reviews={[]}
      faqs={[{"question":"What does a new premium garage door cost in Rockville Centre?","answer":"New installation starts from $800 for standard doors. Premium insulated, carriage-style, and custom wood doors — the styles that suit Canterbury and the village's colonial blocks — run higher depending on size, windows, and finish. We provide a detailed quote before any work begins."},{"question":"Should I repair my garage door or replace it?","answer":"If the door's structure is sound, repair is usually the smarter move — repairs run $150–$300, spring replacement $175–$350, and opener repairs $150–$350. For older doors that drag down an otherwise handsome village colonial, a carriage-style replacement is a high-impact upgrade. We assess honestly and let you decide."},{"question":"What opener do you recommend for a quiet, connected garage?","answer":"We install LiftMaster belt-drive openers with built-in WiFi. They run far quieter than chain drives — essential for attached garages with rooms above — and the smartphone app lets you open, close, and monitor the door from anywhere."},{"question":"Do you offer same-day garage door service in Rockville Centre?","answer":"Our technicians cover Rockville Centre and the surrounding South Shore communities. Same-day appointments are often available, and we give you an exact ETA the moment you call."},{"question":"Can you match a carriage-style door to a Canterbury colonial?","answer":"Yes. We help you choose panel profiles, window grilles, finishes, and hardware that complement brick, stucco, and Tudor revival homes, so the new door looks original to the house. Clean installation and warranty-backed work come standard."},{"question":"My attached garage is right under a bedroom — can you make it quieter?","answer":"That's one of our most common requests in Rockville Centre. A LiftMaster belt-drive opener, nylon rollers, fresh insulated door, and properly balanced springs together eliminate most of the rattle and hum, so early departures and late arrivals don't wake the house."}]}

    />
  );
}
