import LocationPageTemplate from '../../../components/feature/LocationPageTemplate';

export default function LocationPage() {

  return (
    <LocationPageTemplate
      metaTitle="Red Bank, NJ Garage Door Repair & Carriage-House Installation | Smart Garage Doors"
      metaDescription="Garage door repair & premium installation in Red Bank, NJ. Carriage-house doors for Victorian homes, insulated river-climate doors, quiet openers. (914) 557-6816."
      keywords="Red Bank garage door repair, carriage house garage doors Red Bank NJ, garage door installation Red Bank, insulated garage doors Monmouth County, quiet garage door opener Red Bank"
      slug="/red-bank-nj/"
      cityName="Red Bank"
      stateCode="NJ"
      stateName="New Jersey"
      geo={{ latitude: '40.3471', longitude: '-74.0643' }}
      heroImage="https://imagedelivery.net/qHBP5gILWOpC78ZgZPcRpg/251bb224-5425-49d4-7ab9-6fceaf7a3b00/hero"
      neighborhoods={[{"name":"West Side","description":"A walkable neighborhood of Victorians, bungalows, and renovated older homes. Carriage-house doors with period windows and hardware keep the historic streetscape intact while adding modern insulation and quiet openers."},{"name":"East Side near the Navesink","description":"Stately colonials and waterfront homes near the Navesink River. Insulated doors with corrosion-resistant hardware handle the river climate, and quiet belt-drive openers suit attached garages close to living spaces."},{"name":"Fair Haven Border","description":"Tree-lined streets of classic colonials and shingle-style homes along the eastern edge toward Fair Haven. Premium carriage-style and raised-panel doors matched to traditional architecture are the go-to choice here."},{"name":"Little Silver Border","description":"Established single-family neighborhoods near the Little Silver line. Full door-and-opener packages — insulated door, quiet WiFi opener, battery backup — give these homes a complete, warranty-backed upgrade."},{"name":"Shrewsbury Border","description":"Homes along the southern edge toward Shrewsbury, from mid-century ranches to newer builds. Insulated steel doors in modern and traditional profiles fit the mix, with smart openers as a standard recommendation."},{"name":"Broad Street Corridor","description":"Downtown blocks where storefronts, apartments, and converted older buildings meet residential side streets. We handle residential doors on the side streets and light commercial doors and gates along the corridor."}]}
      reviews={[]}
      faqs={[{"question":"Do you install premium and carriage-house garage doors in Red Bank?","answer":"Yes — matching doors to Red Bank's older architecture is a specialty. New installation starts from $800 for standard doors; premium insulated, carriage-style, and custom wood doors run higher. We provide a detailed quote before any work begins, with design options matched to your home."},{"question":"Should I repair my existing door or invest in a new one?","answer":"If the door's structure is sound, repair is usually the smarter move — repairs run $150–$300, spring replacement $175–$350, and opener repairs $150–$350. For older uninsulated doors near the river, an upgrade to an insulated door with weather sealing often makes sense. We assess honestly and let you decide."},{"question":"What opener do you recommend for a quiet, connected garage?","answer":"We typically install LiftMaster belt-drive openers with built-in WiFi. They're the quietest on the market — a real benefit in Red Bank's compact lots and attached garages — and we set up the smartphone app so you can monitor and control the door remotely."},{"question":"How quickly can you get to Red Bank?","answer":"Our Monmouth County technician covers Red Bank and the surrounding river towns. Same-day appointments are often available, and we give you an exact ETA the moment you call."},{"question":"Can you match a garage door to a Victorian or colonial home?","answer":"Yes. We carry carriage-house designs with authentic-looking crossbucks, divided-light windows, and decorative hardware that complement Victorian and colonial architecture on the West Side and East Side. Modern steel and composite construction delivers the historic look with insulation and low maintenance."},{"question":"How do you protect garage doors from the river climate?","answer":"Homes near the Navesink see humidity and salt air that wear on standard hardware. We recommend insulated doors with bottom and perimeter weather sealing, galvanized or stainless hardware, and composite materials that resist swelling and rot — all installed cleanly and backed by warranty."}]}

    />
  );
}
