import LocationPageTemplate from '../../../components/feature/LocationPageTemplate';

export default function LocationPage() {

  return (
    <LocationPageTemplate
      metaTitle="Alpine, NJ Custom Garage Door Installation & Repair | Smart Garage Doors"
      metaDescription="Premium garage door installation & repair in Alpine, NJ. Custom wood estate doors, smart secure openers, discreet clean installation. Licensed & insured. (914) 557-6816."
      keywords="Alpine NJ garage door installation, custom garage doors Alpine, estate garage doors Bergen County, garage door repair Alpine NJ, smart garage door opener Alpine"
      slug="/alpine-nj/"
      cityName="Alpine"
      stateCode="NJ"
      stateName="New Jersey"
      geo={{ latitude: '40.9559', longitude: '-73.9315' }}
      heroImage="https://imagedelivery.net/qHBP5gILWOpC78ZgZPcRpg/251bb224-5425-49d4-7ab9-6fceaf7a3b00/hero"
      neighborhoods={[{"name":"Rio Vista","description":"Alpine's signature gated enclave of grand estates. Oversized custom wood doors, integrated smart access, and security-focused opener systems suit these properties, installed with the discretion gated communities expect."},{"name":"Route 9W Estate Corridor","description":"Sprawling estates set back along Route 9W, many with three-plus-car garages and long private drives. We design and install matched sets of custom and carriage-house doors sized for estate-scale garages."},{"name":"Closter Border","description":"Homes along Alpine's western edge toward Closter, from established colonials to newer luxury builds. Insulated premium doors and quiet belt-drive openers fit attached garages on these residential streets."},{"name":"Demarest Border","description":"The quiet southwestern reaches of Alpine bordering Demarest feature substantial single-family homes. Carriage-style and raised-panel doors with decorative hardware complement the traditional architecture here."},{"name":"Cresskill Border","description":"Luxury homes near the Cresskill line, many recently built or remodeled. Full door-and-opener packages with WiFi control, battery backup, and clean lines are a natural match for these modern properties."},{"name":"Palisades Area","description":"Properties near the Palisades Interstate Park enjoy wooded privacy and dramatic settings. Custom wood and insulated doors stand up to exposure while preserving the natural look these homes are designed around."}]}
      reviews={[]}
      faqs={[{"question":"Do you install custom and premium garage doors in Alpine?","answer":"Yes — estate-grade custom work is our specialty in Alpine. New installation starts from $800 for standard doors; premium insulated, carriage-style, and custom wood doors run higher, especially at oversized estate dimensions. We provide a detailed quote before any work begins, with design options matched to your home."},{"question":"Should I repair my existing door or invest in a new one?","answer":"If the door's structure is sound, repair is usually the smarter move — repairs run $150–$300, spring replacement $175–$350, and opener repairs $150–$350. For older doors on larger Alpine homes, an upgrade to an insulated custom door often improves both performance and curb appeal. We assess honestly and let you decide."},{"question":"What opener do you recommend for a quiet, connected garage?","answer":"We typically install LiftMaster belt-drive openers with built-in WiFi and battery backup. They're the quietest on the market, and we set up the smartphone app so you can monitor and control the door remotely — useful for larger properties and frequent travelers."},{"question":"How quickly can you get to Alpine?","answer":"Our Bergen County technician covers Alpine and the surrounding Northern Valley towns. Same-day appointments are often available, and we give you an exact ETA the moment you call."},{"question":"Can you handle oversized custom wood doors for an Alpine estate?","answer":"Yes. We install oversized and double-wide custom wood doors from premium manufacturers, including matched multi-door sets for three- and four-car garages. We handle the heavier hardware, high-cycle springs, and reinforced tracks these doors require, with clean, warranty-backed installation."},{"question":"Do you offer security and privacy upgrades for gated properties?","answer":"We do. Smart openers with rolling-code remotes, automatic-close timers, smartphone alerts, and battery backup add real security for Rio Vista and the estate corridor. Our technicians work discreetly, coordinate with gate access, and leave the property exactly as we found it."}]}

    />
  );
}
