import LocationPageTemplate from '../../../components/feature/LocationPageTemplate';

export default function LocationPage() {

  return (
    <LocationPageTemplate
      metaTitle="Roslyn, NY Garage Door Repair & Custom Door Installation | Smartest Garage Doors"
      metaDescription="Garage door repair & custom installation in Roslyn, NY. Insulated & custom doors for village and estate homes, quiet smart openers, same-day repair. Licensed & insured. (914) 557-6816."
      keywords="Roslyn garage door repair, garage door installation Roslyn NY, custom garage doors Roslyn Estates, garage door spring replacement Roslyn Heights, garage door opener East Hills"
      slug="/roslyn-ny/"
      cityName="Roslyn"
      stateCode="NY"
      stateName="New York"
      geo={{ latitude: '40.7998', longitude: '-73.6510' }}
      heroImage="https://imagedelivery.net/qHBP5gILWOpC78ZgZPcRpg/251bb224-5425-49d4-7ab9-6fceaf7a3b00/hero"
      neighborhoods={[{"name":"Roslyn Village","description":"One of Long Island's most historic villages, with 18th- and 19th-century homes near the duck pond and Main Street. Carriage-house doors with period-appropriate detailing keep new installations in keeping with the village's historic character."},{"name":"Roslyn Estates","description":"A wooded incorporated village of winding lanes and distinctive custom homes. Custom wood and designer doors are the natural fit here, and we help owners match panel style, finish, and hardware to the house."},{"name":"Roslyn Heights","description":"A large residential area of colonials, splits, and ranches, most with attached one- or two-car garages. Insulated steel doors, spring and cable repairs, and quiet belt-drive opener upgrades cover the most common needs."},{"name":"East Hills","description":"Spacious postwar and newer luxury homes, many with double-car garages. Insulated double doors, smart WiFi openers, and full door-plus-opener packages suit these properties well."},{"name":"Flower Hill & Roslyn Harbor","description":"Estate-style homes between Roslyn and the harbor where weather off Hempstead Harbor wears on doors and hardware. We recommend insulated doors with quality seals and corrosion-resistant components."},{"name":"Greenvale & Albertson borders","description":"We serve the surrounding communities bordering Roslyn with the same services — repairs, spring replacement, opener upgrades, and premium installations."}]}
      reviews={[]}
      faqs={[{"question":"What does a new garage door installation cost in Roslyn?","answer":"New installation starts from $800 for standard doors; premium insulated, carriage-style, and custom wood doors run higher. You receive a detailed quote before any work begins — door, hardware, and labor all itemized."},{"question":"Is it better to repair or replace my Roslyn garage door?","answer":"If the panels and frame are solid, repair is usually the right call: most repairs run $150–$300, spring replacement $175–$350, and opener repairs $150–$350. If the door is uninsulated, warped, or breaking down repeatedly, replacement is often the better investment. We assess on site and give you an honest recommendation."},{"question":"Can you upgrade me to a quiet opener with smartphone control?","answer":"Yes. We install LiftMaster belt-drive openers — the quietest option for attached garages — and handle the full WiFi app setup so you can open, close, and monitor the door from anywhere. Remotes and keypads are programmed before we leave."},{"question":"How fast can you get to Roslyn?","answer":"Our North Shore team covers Roslyn and the surrounding villages every week. We give you an honest ETA when you call, and same-day appointments are often available."},{"question":"Can you install a door that suits a historic Roslyn Village home?","answer":"Yes. For older village homes we recommend carriage-house designs with traditional proportions, divided-light windows, and decorative hardware that read as period-appropriate while delivering modern insulation and safety. If your property has village or HOA design guidelines, we'll work within them and provide spec sheets for any approval process."},{"question":"What do you recommend for opener upgrades in East Hills and Roslyn Heights?","answer":"For attached garages we recommend replacing older chain-drive units with a LiftMaster belt-drive — quieter, smoother, and WiFi-enabled. Opener repairs run $150–$350 when the existing unit is worth saving; if it's decades old or lacks modern safety reversal, we'll suggest replacement and quote both options upfront."}]}

    />
  );
}
