import LocationPageTemplate from '../../../components/feature/LocationPageTemplate';

export default function LocationPage() {

  return (
    <LocationPageTemplate
      metaTitle="Oyster Bay, NY Garage Door Repair & Custom Wood Door Installation | Smart Garage Doors"
      metaDescription="Garage door repair & custom installation in Oyster Bay, NY. Salt-air resistant hardware, custom wood doors, estate-scale installs for waterfront homes. (914) 557-6816."
      keywords="Oyster Bay garage door repair, custom wood garage doors Oyster Bay, garage door installation Oyster Bay NY, waterfront garage doors Nassau County, garage door opener Mill Neck"
      slug="/oyster-bay-ny/"
      cityName="Oyster Bay"
      stateCode="NY"
      stateName="New York"
      geo={{ latitude: '40.8657', longitude: '-73.5321' }}
      heroImage="https://imagedelivery.net/qHBP5gILWOpC78ZgZPcRpg/251bb224-5425-49d4-7ab9-6fceaf7a3b00/hero"
      neighborhoods={[{"name":"Oyster Bay hamlet","description":"Historic Victorians, colonials, and village homes near the harbor and Main Street. Period-appropriate carriage-house doors with decorative hardware keep these properties true to their character while adding modern insulation."},{"name":"Cove Neck","description":"Secluded waterfront estates on the peninsula east of the harbor. Custom wood doors, oversized openings, and integrated smart opener and gate systems suit these landmark-caliber properties."},{"name":"Mill Neck","description":"Wooded estate properties with carriage houses and detached garages. We design custom wood and faux-wood overlay doors that complement stone, shingle, and Tudor architecture, installed with premium corrosion-resistant hardware."},{"name":"Centre Island","description":"Homes surrounded by water on nearly every side, where salt air is relentless. Marine-grade hardware, sealed finishes, and corrosion-resistant springs and tracks are essential — and standard in our installs here."},{"name":"Bayville","description":"Beach colonials and capes along the Sound-facing strip. Insulated steel doors with baked-on coastal finishes and stainless fasteners stand up to salt spray far better than builder-grade doors."},{"name":"East Norwich","description":"Established colonials and newer builds along the Route 25A corridor. We provide everything from spring and opener repairs to full premium door-and-opener packages with warranty-backed installation."}]}
      reviews={[]}
      faqs={[{"question":"What does a premium garage door installation cost in Oyster Bay?","answer":"New installation starts from $800 for standard doors. Premium insulated, carriage-style, and custom wood doors — the styles most at home in Oyster Bay and Mill Neck — run higher depending on size, species, and finish. We provide a detailed quote before any work begins."},{"question":"Should I repair my existing garage door or replace it?","answer":"If the door's structure is sound, repair is usually the smarter move — repairs run $150–$300, spring replacement $175–$350, and opener repairs $150–$350. If salt air has corroded panels, tracks, or hardware beyond surface rust, replacement with coastal-grade components is the better long-term investment. We assess honestly and let you decide."},{"question":"What opener do you recommend for a quiet, connected garage?","answer":"We install LiftMaster belt-drive openers with built-in WiFi. They're the quietest on the market, and the smartphone app lets you monitor and control the door remotely — valuable for estate properties and second homes on the water."},{"question":"Do you offer same-day garage door service in Oyster Bay?","answer":"Our technicians cover Oyster Bay and the surrounding communities, from the hamlet out to Bayville and Centre Island. Same-day appointments are often available, and we give you an exact ETA the moment you call."},{"question":"How do you protect garage doors from salt air in Centre Island and Bayville?","answer":"Waterfront homes need more than a standard install. We use galvanized or stainless tracks and fasteners, corrosion-resistant springs, sealed bottom retainers, and doors with baked-on or marine-grade finishes. These premium parts cost more up front but dramatically outlast standard hardware in salt-air exposure."},{"question":"Can you handle estate-scale and custom wood door projects?","answer":"Yes. For Cove Neck and Mill Neck estates we install custom wood and faux-wood overlay doors in oversized and multi-bay configurations, coordinating designs with architects and property managers where needed. Every project gets a detailed proposal, premium hardware, clean installation, and warranty-backed work."}]}

    />
  );
}
