import LocationPageTemplate from '../../../components/feature/LocationPageTemplate';

export default function LocationPage() {

  return (
    <LocationPageTemplate
      metaTitle="Harrison, NY Custom Garage Door Installation & Repair | Smartest Garage Doors"
      metaDescription="Garage door repair & custom installation in Harrison, NY. Custom doors for estates & colonials, quiet belt-drive openers, full packages. Licensed & insured. (914) 557-6816."
      keywords="Harrison garage door repair, custom garage doors Harrison NY, garage door installation Purchase NY, quiet garage door opener Harrison, carriage house garage doors Westchester"
      slug="/harrison-ny/"
      cityName="Harrison"
      stateCode="NY"
      stateName="New York"
      geo={{ latitude: '41.0237', longitude: '-73.7124' }}
      heroImage="https://imagedelivery.net/qHBP5gILWOpC78ZgZPcRpg/251bb224-5425-49d4-7ab9-6fceaf7a3b00/hero"
      neighborhoods={[{"name":"Purchase","description":"Estate properties on generous lots, many with multi-bay and detached garages. Custom wood and carriage-style doors at estate scale, paired with smart openers and battery backup, suit these homes perfectly."},{"name":"West Harrison","description":"A close-knit neighborhood of well-kept colonials and capes near Silver Lake. Insulated steel and carriage-style doors with quiet belt-drive openers deliver comfort and curb appeal at a fair, upfront price."},{"name":"Downtown Harrison","description":"Residential blocks around the train station where attached garages sit close to living space. Quiet belt-drive openers and insulated doors keep noise down and comfort up for commuter households."},{"name":"Sterling Ridge","description":"A premier neighborhood of substantial colonials and custom builds. We match raised-panel, carriage-house, and full-custom designs to each home's architecture, with premium parts and warranty-backed installation."},{"name":"Park Lane area","description":"Quiet streets of classic Harrison homes where a dated door stands out. Full door-and-opener packages — premium insulated door, LiftMaster belt-drive opener, new tracks and springs — refresh the whole system at once."},{"name":"Golf club corridors","description":"Homes near Harrison's golf course corridors tend toward classic colonial and estate styles. Custom doors with traditional profiles, divided-light windows, and decorative hardware complement these properties beautifully."}]}
      reviews={[]}
      faqs={[{"question":"Do you install custom and premium garage doors in Harrison?","answer":"Yes — custom work is a specialty here. New installation starts from $800 for standard doors; premium insulated, carriage-style, and custom wood doors run higher. We provide a detailed quote before any work begins, with design options matched to your home's architecture."},{"question":"Should I repair my existing door or invest in a new one?","answer":"If the door's structure is sound, repair is usually the smarter move — repairs run $150–$300, spring replacement $175–$350, and opener repairs $150–$350. For older uninsulated doors on larger Harrison homes, an upgrade to an insulated custom door often improves both energy efficiency and curb appeal. We assess honestly and let you decide."},{"question":"What opener do you recommend for a quiet, connected garage?","answer":"We typically install LiftMaster belt-drive openers with built-in WiFi and battery backup. They're the quietest on the market — important when the garage sits below a bedroom — and the smartphone app lets you monitor and control the door from anywhere."},{"question":"How quickly can you get to Harrison?","answer":"Our Westchester-area technician covers Harrison, Purchase, West Harrison, and the surrounding communities. Same-day appointments are often available, and we give you an exact ETA the moment you call."},{"question":"Can you handle estate-scale garages in Purchase?","answer":"Yes. Purchase properties often have three- and four-bay or detached garages, and we install oversized custom doors with coordinated styles, finishes, and hardware across every bay. Each door gets properly rated springs and its own opener, all installed cleanly and warranty-backed."},{"question":"Do you offer complete door-and-opener packages?","answer":"We do, and they're popular in Harrison. A full package includes a premium insulated or carriage-style door, a LiftMaster belt-drive opener with WiFi, new springs, tracks, and weather sealing — one visit, one upfront price, and a single warranty covering the whole system."}]}

    />
  );
}
