import LocationPageTemplate from '../../../components/feature/LocationPageTemplate';

export default function LocationPage() {

  return (
    <LocationPageTemplate
      metaTitle="Old Westbury, NY Custom Garage Door Installation & Estate Door Service | Smartest Garage Doors"
      metaDescription="Custom garage door installation & repair in Old Westbury, NY. Estate-scale wood doors, oversized multi-bay garages, smart openers. Licensed & insured. (914) 557-6816."
      keywords="Old Westbury garage door installation, custom garage doors Old Westbury, estate garage doors Nassau County, oversized garage doors Old Westbury NY, garage door repair Old Westbury"
      slug="/old-westbury-ny/"
      cityName="Old Westbury"
      stateCode="NY"
      stateName="New York"
      geo={{ latitude: '40.7887', longitude: '-73.5996' }}
      heroImage="https://imagedelivery.net/qHBP5gILWOpC78ZgZPcRpg/251bb224-5425-49d4-7ab9-6fceaf7a3b00/hero"
      neighborhoods={[{"name":"Old Westbury Estates","description":"Gated properties with long driveways and multi-bay garages call for estate-scale solutions. We install oversized custom wood doors, coordinate finishes across three- and four-bay garages, and integrate smart access for the whole property."},{"name":"Brookville","description":"Substantial homes on large wooded lots where detached and oversized garages are common. Premium insulated doors and quiet belt-drive openers with battery backup keep these garages working through any season."},{"name":"Upper Brookville","description":"Secluded estates where security and privacy come first. We pair custom doors with rolling-code smart openers, smartphone alerts, and automatic-close timers so the garage is never an open question."},{"name":"Muttontown","description":"Sprawling properties with carriage houses and outbuildings alongside the main garage. Carriage-style and custom wood doors keep every structure architecturally consistent, all installed cleanly and warranty-backed."},{"name":"Wheatley Hills","description":"Classic North Shore colonials and newer custom builds near the golf course. Raised-panel, carriage-house, and full-custom designs let us match the door to the home rather than the other way around."},{"name":"Store Hill Road corridor","description":"Homes along and around the historic Store Hill Road corridor, where curb appeal matters. We help owners select profiles, windows, and hardware that complement estate-style architecture, with upfront pricing on every option."}]}
      reviews={[]}
      faqs={[{"question":"Do you install custom and estate-scale garage doors in Old Westbury?","answer":"Yes — large custom work is our specialty in Old Westbury. New installation starts from $800 for standard doors; premium insulated, carriage-style, and custom wood doors, including oversized and multi-bay configurations, run higher. We provide a detailed quote before any work begins."},{"question":"Should I repair my existing door or invest in a new one?","answer":"If the door's structure is sound, repair is usually the smarter move — repairs run $150–$300, spring replacement $175–$350, and opener repairs $150–$350. For older doors on larger Old Westbury homes, upgrading to an insulated custom door often pays off in energy efficiency and curb appeal. We assess honestly and let you decide."},{"question":"What opener do you recommend for a quiet, connected garage?","answer":"We typically install LiftMaster belt-drive openers with built-in WiFi and battery backup. They're the quietest on the market, and the smartphone app lets you monitor and control every door remotely — especially useful on larger properties with multiple garage bays."},{"question":"How quickly can you get to Old Westbury?","answer":"Our technicians covering the North Shore serve Old Westbury and the surrounding communities. Same-day appointments are often available, and we give you an exact ETA the moment you call."},{"question":"Can you handle a three- or four-bay garage with matching doors?","answer":"Absolutely. Multi-bay garages are common on Old Westbury estates, and we coordinate door styles, finishes, windows, and hardware across every bay for a unified look. Each door gets its own properly rated springs and opener, installed cleanly and warranty-backed."},{"question":"Can you integrate the garage with our gate and security systems?","answer":"Yes. Smart openers with rolling-code remotes, smartphone alerts, automatic-close timers, and battery backup add real security for gated Old Westbury properties. We can include these features in any door-and-opener package and coordinate access alongside your existing gate setup."}]}

    />
  );
}
