import LocationPageTemplate from '../../../components/feature/LocationPageTemplate';

export default function LocationPage() {

  return (
    <LocationPageTemplate
      metaTitle="Colts Neck, NJ Custom Garage Door Installation & Repair | Smartest Garage Doors"
      metaDescription="Premium garage door installation & repair in Colts Neck, NJ. Estate-scale custom doors, three-car garage packages, smart openers. Licensed & insured. (914) 557-6816."
      keywords="Colts Neck garage door installation, custom garage doors Colts Neck NJ, estate garage doors Monmouth County, garage door repair Colts Neck, three car garage doors Colts Neck"
      slug="/colts-neck-nj/"
      cityName="Colts Neck"
      stateCode="NJ"
      stateName="New Jersey"
      geo={{ latitude: '40.2890', longitude: '-74.1660' }}
      heroImage="https://imagedelivery.net/qHBP5gILWOpC78ZgZPcRpg/251bb224-5425-49d4-7ab9-6fceaf7a3b00/hero"
      neighborhoods={[{"name":"Route 537 Horse-Farm Estates","description":"Equestrian properties and working horse farms along the Route 537 corridor, often with barns and multi-bay garages. Custom wood and carriage-house doors at estate scale, plus heavy-duty hardware built for daily use, suit these properties."},{"name":"Clover Hill","description":"Luxury homes on generous lots, many with three-plus-car garages. We install matched sets of premium insulated doors with quiet belt-drive openers and battery backup as complete door-and-opener packages."},{"name":"Five Points","description":"The historic crossroads at the center of town, surrounded by established colonials and farmhouse-style homes. Carriage-style doors with decorative hardware echo the area's rural character while adding modern insulation."},{"name":"Montrose Corridor","description":"Newer luxury builds and custom homes along Montrose Road. Full-view, custom wood, and designer steel doors give these architect-designed homes a finished look, with WiFi openers integrated from day one."},{"name":"Yellow Brook Area","description":"Homes near Yellow Brook and the surrounding countryside, where long driveways and detached garages are common. Insulated doors and smart openers with smartphone alerts let you check the garage without walking out to it."},{"name":"Heyers Mill","description":"A quiet pocket of substantial single-family homes near the historic mill site. Premium raised-panel and carriage-house doors, installed cleanly and backed by warranty, fit the neighborhood's traditional look."}]}
      reviews={[]}
      faqs={[{"question":"Do you install custom and estate-scale garage doors in Colts Neck?","answer":"Yes — estate work is a specialty here. New installation starts from $800 for standard doors; premium insulated, carriage-style, and custom wood doors run higher, particularly at oversized dimensions. We provide a detailed quote before any work begins, with design options matched to your property."},{"question":"Should I repair my existing door or invest in a new one?","answer":"If the door's structure is sound, repair is usually the smarter move — repairs run $150–$300, spring replacement $175–$350, and opener repairs $150–$350. For older doors on larger Colts Neck homes, an upgrade to an insulated custom door often improves both performance and curb appeal. We assess honestly and let you decide."},{"question":"What opener do you recommend for a quiet, connected garage?","answer":"We typically install LiftMaster belt-drive openers with built-in WiFi and battery backup — a smart addition on larger rural lots where power interruptions happen. We set up the smartphone app so you can monitor and control every door remotely."},{"question":"How quickly can you get to Colts Neck?","answer":"Our Monmouth County technician covers Colts Neck and the surrounding towns. Same-day appointments are often available, and we give you an exact ETA the moment you call."},{"question":"Can you outfit a three- or four-car garage with matching doors?","answer":"Yes. We design and install matched multi-door sets for three-plus-car garages — common in Clover Hill and along Montrose — including coordinated finishes, windows, and hardware. Complete packages cover doors, high-cycle springs, openers, and battery backup in one warranty-backed installation."},{"question":"Do you work on barn and outbuilding doors for equestrian properties?","answer":"We do. Horse-farm estates along Route 537 often have barns and outbuildings with overhead doors that see heavy daily use. We install and service heavy-duty sectional doors, reinforced tracks, and high-cycle springs built for that workload, alongside the main house garage."}]}

    />
  );
}
