import LocationPageTemplate from '../../../components/feature/LocationPageTemplate';

export default function LocationPage() {

  return (
    <LocationPageTemplate
      metaTitle="Port Washington, NY Garage Door Repair & Custom Door Installation | Smartest Garage Doors"
      metaDescription="Garage door repair & installation in Port Washington, NY. Insulated, salt-air-resistant doors, quiet smart openers, same-day repair. Licensed & insured. (914) 557-6816."
      keywords="Port Washington garage door repair, garage door installation Port Washington NY, insulated garage doors Port Washington, garage door spring replacement Port Washington, smart garage door opener Nassau County"
      slug="/port-washington-ny/"
      cityName="Port Washington"
      stateCode="NY"
      stateName="New York"
      geo={{ latitude: '40.8257', longitude: '-73.6982' }}
      heroImage="https://imagedelivery.net/qHBP5gILWOpC78ZgZPcRpg/251bb224-5425-49d4-7ab9-6fceaf7a3b00/hero"
      neighborhoods={[{"name":"Sands Point","description":"Grand waterfront estates facing Manhasset Bay and the Sound. For homes this exposed to salt air, we recommend insulated steel or composite doors with marine-grade hardware and corrosion-resistant springs and tracks."},{"name":"Baxter Estates","description":"A charming incorporated village of classic colonials and Tudors near the harbor. We install carriage-style and custom doors that complement the village's traditional architecture, paired with quiet belt-drive openers."},{"name":"Manorhaven","description":"A waterfront community of capes, splits, and newer rebuilds along the bay. Salt air is hard on hardware here, so we offer galvanized tracks, stainless fasteners, and weather-sealed insulated doors built for the shoreline."},{"name":"Port Washington North","description":"Established residential streets with mid-century colonials and ranches. We handle everything from spring and cable replacement to full insulated door upgrades and WiFi smart opener installs."},{"name":"Flower Hill border","description":"Larger lots and stately homes on the Flower Hill side of town. Architectural matching matters here — we help homeowners choose carriage-house and custom panel designs that suit the home."},{"name":"Soundview & Salem area","description":"Family neighborhoods of well-kept splits and colonials. Popular projects include insulated door replacements for attached garages and quiet LiftMaster belt-drive openers for bedrooms above the garage."}]}
      reviews={[]}
      faqs={[{"question":"What does a new garage door installation cost in Port Washington?","answer":"New installation starts from $800 for standard doors; premium insulated, carriage-style, and custom wood doors run higher. We provide a detailed quote before any work begins, so you know the exact price upfront."},{"question":"Should I repair or replace my garage door in Port Washington?","answer":"If the door panels are sound, most issues — broken springs ($175–$350), frayed cables, bent tracks, opener faults ($150–$350) — are worth repairing, with most repairs running $150–$300. If panels are rusted through, badly dented, or the door is uninsulated and decades old, replacement is usually the better long-term investment. We give you an honest assessment either way."},{"question":"Can you make my garage door quieter and add smartphone control?","answer":"Yes. We install LiftMaster belt-drive openers that run far quieter than old chain drives — ideal when there's living space above or beside the garage. Every install includes full WiFi setup, so you can open, close, and monitor the door from the myQ app."},{"question":"How fast can you get to Port Washington?","answer":"Our North Shore team covers Port Washington and the surrounding peninsula every week, so a technician is never far away. We give you an honest ETA when you call, and same-day appointments are often available."},{"question":"How do you protect garage doors from salt air near Manhasset Bay?","answer":"Homes in Sands Point, Manorhaven, and along the bay see real salt-air corrosion. We recommend insulated steel or composite doors with factory-baked finishes, galvanized tracks, stainless-steel hinges and fasteners, and corrosion-resistant springs — plus periodic lubrication and weather-seal checks."},{"question":"Can you match a garage door to my colonial or Tudor home?","answer":"Absolutely. Port Washington and Baxter Estates have beautiful traditional architecture, and we help you choose carriage-house designs, raised panels, window inserts, and finishes from Clopay, Wayne Dalton, and Amarr that complement the home rather than fight it."}]}

    />
  );
}
